# List time calculation

In [2]:
import numpy

In [3]:
import numpy as np

In [3]:
%timeit [(i ** 2) for i in range (1,100+1)]

10.8 µs ± 92.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%%timeit 

li = []
for i in range(1,100+1):
    li.append(i ** 2)

12.1 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Numpy Array time calculation

In [5]:
%timeit (np.arange(1,100+1))**2 

2.58 µs ± 59.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [ ]:
li = [1, 2, 3, 4]

# Creating numpy array
y = np.array(li)

# Printing array 
print(x)

# Printing type of array
print(type(x))               # ndarray = n dimensional array

6
<class 'int'>


In [10]:
# Creating empty list 
l = []

# Running for loop from 1 to 5
for i in range(1,6):

    # Getting input from user in int format 
    x = int(input("Enter no : "))

    # Appending the value to list l
    l.append(x)
    
# Converting list to numpy array and printing
print(np.array(l))



Enter no :  2
Enter no :  3
Enter no :  4
Enter no :  5
Enter no :  6


[2 3 4 5 6]


In [17]:
# Count for 1D array in function (.ndim)

print(y.ndim) 
print(np.array(l).ndim)

1
1


In [19]:
# For 2D array 

# Creating a 2D np array 
arr2 = np.array([ [1, 2, 3, 4, 5]]) 

# Printing arr2
print(arr2)

# Printing dimensions of arr2
print(arr2.ndim)



[[1 2 3 4 5]]
2


In [23]:
# For 2D array (multiple array create kar sakte hai)

# Creating a 2D np array 
arr2 = np.array([ [1, 2, 3, 4, 5],[6,7,8,9,10]]) 

# Printing arr2
print(arr2)

# Printing dimensions of arr2
print(arr2.ndim)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [25]:
# Creating 3 by 3 2D array 

arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr3)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [26]:
# For 3D array 

# Creating a 3D np array 
arr3d = np.array([[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]]) 

# Printing arr2
print(arr3d)

# Printing dimensions of arr2
print(arr3d.ndim)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [30]:
# For n-D array 

# Creating a n-D np array 

arrn = np.array([1,2,3,4,5], ndmin = 10)   # Using ndmin keyword

#Printing n - dimensional array
print(arrn)

#printing dimensions of arrn
print(arrn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [4]:
# For n-D array 

# Creating a n-D np array 

arrn = np.array([1,2,3,4,5], ndmin = 5)   # Using ndmin keyword

#Printing n - dimensional array
print(arrn)

#printing dimensions of arrn
print(arrn.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Zeros

In [4]:
# Creating special numpy array

# Creating zeros numpy array (1D)
ar_zeros = np.zeros(5)         # 1D array ke liye hai 

# Printing ar_zeros
print(ar_zeros)

[0. 0. 0. 0. 0.]


In [7]:
# Creating zeros numpy array (2D)
ar_zeros1 = np.zeros((3,2))         # 2D array ke liye hai (3 rows , 2 columns) 

# Printing ar_zeros
print(ar_zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
# Creating zeros numpy array (3D)
ar_zeros2 = np.zeros((4,3,2))         # 3D array ke liye hai (4 size aur depth,  3 rows , 2 columns) 

# Printing ar_zeros
print(ar_zeros2)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


# Ones

In [12]:
# Creating ones numpy array (1D)
ar_ones = np.ones(3)

# Printing ar_ones
print(ar_ones)

[1. 1. 1.]


In [14]:
# Creating ones numpy array (2D)
ar_ones1 = np.ones((5,3))         # 2D array ke liye hai (3 rows , 2 columns) 

# Printing ar_zeros
print(ar_ones1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Empty Array

In [21]:
# Creating empty numpy array  (Previous ka leta hai)
ar_em = np.empty(3)

# Printing ar_em
print(ar_em)

[1. 1. 1.]


# Range

In [5]:
# Creating range using numpy array 
arr_rn = np.arange(4)

# Printing arr_rn (Range)
print(arr_rn)

[0 1 2 3]


In [3]:
# In Creating Range of elements in numpy array we having 2 forms. 
# np.arange() or np.linspace() use karte hai.
# 2D and 3D use karna ho hume reshape() function use karna padega.

# np.arange()  1D

ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


In [5]:
# np.arange()   we usnig start, stop, step method  

arr_rn1 = np.arange(1, 10, 2)    # 1 - start, 10 - stop, 2 - step
print(arr_rn1)

[1 3 5 7 9]


In [9]:
# For 2D ,3D we using .reshape() function

# For 2D 

ar_rn2 = np.arange(1, 13).reshape(3,4)
print(ar_rn2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# For 3D 

ar_rn3 = np.arange(1,25).reshape(2,4,3)
print(ar_rn3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


# Diagonal

In [6]:
# Creating diagnonal array with 1s means iske sare diagonal 1 hoge.

# Indentity matrix

arr_dia = np.eye(4)

print(arr_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# Non - Square Matrix

arr_dia1 = np.eye(3,5)
print(arr_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linspace

In [6]:
# np.linspace()   we use start, stop, numm

arr_ls = np.linspace(1, 10, num = 5)   # 1- start, 10- stop, 5-num of elements
print(arr_ls)

[ 1.    3.25  5.5   7.75 10.  ]
