# Difference Between Python List vs Numpy Array

In [10]:
import numpy

In [11]:
import numpy as np

In [6]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
y = [1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


# List time calculation

In [15]:
%timeit [(i ** 2) for i in range (1,100+1)]

10.7 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%%timeit 

li = []
for i in range (1,100+1):
    li.append(i ** 2)

11.8 µs ± 80.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Numpy Array time calculation

In [16]:
%timeit (np.arange(1,100+1))**2 

2.81 µs ± 49 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [23]:
li = [1, 2, 3, 4]

# Creating numpy array
x = np.array(li)

# Printing array 
print(x)

# Printing type of array
print(type(x))               # ndarray = n dimensional array

[1 2 3 4]
<class 'numpy.ndarray'>


In [24]:
# Creating empty list 
l = []

# Running for loop from 1 to 5
for i in range(1,6):

    # Getting input from user in int format 
    x = int(input("Enter no : "))

    # Appending the value to list l
    l.append(x)
    
# Converting list to numpy array and printing
print(np.array(l))
    

Enter no :  2
Enter no :  3
Enter no :  4
Enter no :  5
Enter no :  6


[2 3 4 5 6]
