# Arithmetic Operation

In [1]:
import numpy 

In [2]:
import numpy as np

In [6]:
# 1D Array for arithmetic operation    
# Addition 
var = np.array([1, 2, 3, 4, 5])    # Means isme humne jo (var + 4) diya hai wo var me add hoga.
                                   #  Jaise 4+1, 4+2, 4+3, 4+4, 4+5 
var_add = var + 4 

print(var_add)

[5 6 7 8 9]


In [7]:
# Subtraction 

var = np.array([1, 2, 3, 4, 5])    # Means isme humne jo (var - 4) diya hai wo var me add hoga.
                                   #  Jaise 4-1, 4-2, 4-3, 4-4, 4-5 
var_add = var - 4 

print(var_add)


[-3 -2 -1  0  1]


In [8]:
# Multiplication 

var = np.array([1, 2, 3, 4, 5])

var_add = var * 4

print(var_add) 

[ 4  8 12 16 20]


In [9]:
# Division 

var = np.array([1, 2, 3, 4, 5])

var_add = var / 4

print(var_add)


[0.25 0.5  0.75 1.   1.25]


In [9]:
# Reciprocal 

var = np.array([1, 2, 3, 4, 5])

var_add = np.reciprocal(var)
print(var_add)

[1 0 0 0 0]


In [10]:
# 2D 

var1 = np.array([1, 2, 3, 4, 5])
var2 = np.array([1, 2, 3, 4, 5])

var_add = var1 + var2

print(var_add)

[ 2  4  6  8 10]


# Using functions

In [9]:
# Addition
# 1D

var = np.array([1, 2, 3, 4, 5])    # Means isme humne jo (np.add) use kiya jo var me and usme 3 add kiya. 
var_add = np.add(var, 3) 

print(var_add)

[4 5 6 7 8]


In [11]:
# 2D 


var1 = np.array([1, 2, 3, 4, 5])
var2 = np.array([1, 2, 3, 4, 5])

var_add = np.add(var1, var2)

print(var_add)

[ 2  4  6  8 10]


In [4]:
# Agar usme number add karna hoga to.

var1 = np.array([1, 2, 3, 4, 5])
var2 = np.array([1, 2, 3, 4, 5])

var_add = np.add(var1, 4)

print(var_add)


[5 6 7 8 9]


# 2D array

In [7]:
# addition
var10 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var20 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var10)
print()
print(var20)
print()

var_add2 = var10 + var20 
print(var_add2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [8]:
# multiplication 

var10 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var20 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var10)
print()
print(var20)
print()

var_add2 = var10 * var20 
print(var_add2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


# Arithmetic Functions

In [18]:
# Max and Min 

var = np.array([1, 2, 3, 4, 5, 6, 2, 4])
print("Max : " ,np.max(var))

# Min 
var = np.array([1, 2, 3, 4, 5, 6, 2, 4])
print("Min : " ,np.min(var))


Max :  6
Min :  1


In [19]:
# argmin and argmax meaning ki min and max ki position kaha hai batata hai.

var = np.array([1, 2, 3, 4, 5, 6, 2, 4])
print("Max : " ,np.max(var), np.argmax(var))

# Min 
var = np.array([1, 2, 3, 4, 5, 6, 2, 4])
print("Min : " ,np.min(var), np.argmin(var))


Max :  6 5
Min :  1 0


In [24]:
# 2D array         

var1 = np.array([[2, 1, 3],[9, 5, 6]])               # axis = 0 means column
                                                     # axis = 1 means row
print(np.min(var1,axis = 1))                         # [2,1,3]   for row 1
                                                     # [9,5,6]           5
                                         # for col min [2 1 3 ]


[1 5]


## sqrt 

In [25]:
# sqrt = square root 

var = np.array([1, 2, 3, 4, 5, 6, 2, 4])
print("sqrt : ", np.sqrt(var)) 


sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 1.41421356 2.        ]


## sin and cos function

In [28]:
# For sin
var = np.array([1, 2, 3])

print(np.sin(var))

# For cos 
var = np.array([1, 2, 3])

print(np.cos(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
