# Data Type Functions

In [3]:
import numpy

In [4]:
import numpy as np

In [9]:
# Finding data type 

# For integer

var = np.array([1,2,3,4,5,11,12,13,14,15])

print("Data Type : ",var.dtype)

Data Type :  int64


In [8]:
var = np.array([1,2,3,4,5])

print("Data Type : ",var.dtype)

Data Type :  int64


In [12]:
# For float 

var1 = np.array([1.0,2.5,3.7,4.3,5.11])

print("Data Type : ",var.dtype)


Data Type :  float64


In [13]:
# For String 

var2 = np.array(['a','b','c','d'])
print("Data Type : ",var2.dtype)

Data Type :  <U1


In [14]:
# String + Numbers 

var2 = np.array(['a','b','c','d',1,2,3,4,5])
print("Data Type : ",var2.dtype)

Data Type :  <U21


## Changing datatype like (int8 replace to int32)

In [22]:
# int64

x = np.array([1,2,3,4,5])

print("Data Type : ",x.dtype)

Data Type :  int64


In [23]:
# changing (int64 to int8)

x = np.array([1,2,3,4,5], dtype = np.int8)

print("Data Type : ",x.dtype)
print(x)

Data Type :  int8
[1 2 3 4 5]


In [28]:
# Converting int into float 

x1 = np.array([1,2,3,4,5], dtype = "f")

print("Data Type : ",x1.dtype)
print(x1)


Data Type :  float32
[1. 2. 3. 4. 5.]


In [30]:
# converting datatypes

x2 = np.array([1,2,3,4,5])

# Converting int to float32
New = np.float32(x2)

# Converting float to int16
New_1 = np.int16(New)
print("Data Type : ",x2.dtype)
print("Data Type : ",New.dtype)
print("Data Type : ",New_1.dtype)
print(x2) 
print(New)
print(New_1)


Data Type :  int64
Data Type :  float32
Data Type :  int16
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]
