# Random

## Rand()

In [2]:
import numpy

In [3]:
import numpy as np

In [4]:
# Creating numpy array with random numbers 

# 1D

var = np.random.rand(4)
print(var)

[0.50516259 0.20217249 0.38831539 0.05768848]


In [4]:
# 2D 

var_2 = np.random.rand(2,3)
print(var_2)

[[0.57013027 0.9309724  0.67689368]
 [0.79135458 0.37282493 0.76982656]]


In [5]:
# 3D

var_3 = np.random.rand(2,3,4)
print(var_3)

[[[0.97636702 0.55306779 0.49954818 0.79698084]
  [0.44341453 0.05046797 0.90109035 0.28770401]
  [0.3981055  0.37302616 0.10698562 0.8489519 ]]

 [[0.13438652 0.9426341  0.21674296 0.569022  ]
  [0.74301321 0.90244712 0.22328478 0.26255909]
  [0.18046685 0.89546437 0.63058185 0.70570921]]]
